'use client';
import {AreaChart,Area,CartesianGrid,XAxis,YAxis,Tooltip,ResponsiveContainer} from 'recharts';
import {ArrowUpRight} from 'lucide-react';
import {money,number,percent,dateLabel} from '@/lib/api';
import type {Trend,Breakdown,Retry} from '@/lib/types';
import {EmptyState} from './ui';

export function PerformanceChart({data}:{data:Trend[]}){return <><div className="chart-legend"><span><i className="legend-line green"/> Settled volume</span><span><i className="legend-line dark"/> Failed value</span><span className="chart-unit">EUR · daily</span></div><div className="performance-chart" role="img" aria-label={`Daily settled and failed payment values in euros across ${data.length} days. Settled total ${money(data.reduce((n,d)=>n+Number(d.processed_volume),0),false)}.`}><ResponsiveContainer width="100%" height="100%"><AreaChart data={data} margin={{top:18,right:10,left:-15,bottom:5}}><defs><linearGradient id="volume-fill" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor="#78ff00" stopOpacity={.20}/><stop offset="100%" stopColor="#78ff00" stopOpacity={0}/></linearGradient></defs><CartesianGrid strokeDasharray="3 5" vertical={false} stroke="#e6e8e1"/><XAxis dataKey="day" tickFormatter={dateLabel} tickLine={false} axisLine={false} minTickGap={55} tick={{fill:'#75786f',fontSize:12}} dy={10}/><YAxis tickFormatter={v=>money(v)} tickLine={false} axisLine={false} tick={{fill:'#75786f',fontSize:12}}/><Tooltip labelFormatter={v=>dateLabel(String(v))} formatter={(v,name)=>[money(Number(v),false),name==='processed_volume'?'Settled volume':'Failed value']} contentStyle={{borderRadius:12,border:'1px solid #e5e6e0',fontSize:14}}/><Area type="monotone" dataKey="processed_volume" stroke="#65c800" strokeWidth={2.5} fill="url(#volume-fill)" isAnimationActive={false}/><Area type="monotone" dataKey="failed_value" stroke="#30322b" strokeWidth={1.8} fill="transparent" isAnimationActive={false}/></AreaChart></ResponsiveContainer></div></>}
export function FailureBars({data,onSelect}:{data:Breakdown[];onSelect:(name:string)=>void}){const max=Math.max(...data.map(x=>Number(x.failed_value)),1);return data.length?<div className="failure-bars">{data.map((d,i)=><button className="bar-row" key={d.key} onClick={()=>onSelect(d.name)}><div className="bar-label"><span>{d.name}</span><strong>{money(d.failed_value)}</strong></div><div className="bar-track"><span style={{width:`${Number(d.failed_value)/max*100}%`}} className={i===0?'accent':''}/></div></button>)}</div>:<EmptyState text="No failed payments in this period."/>}
export function CountryRanks({data,onSelect,limit}:{data:Breakdown[];onSelect:(country:string)=>void;limit?:number}){const sorted=[...data].sort((a,b)=>(a.success_rate??101)-(b.success_rate??101));return data.length?<div className="country-ranks"><div className="rank-header"><span>Market</span><span>Payments</span><span>Success rate</span></div>{sorted.slice(0,limit).map(d=><button key={d.key} onClick={()=>onSelect(d.key)} className="rank-row"><span className="market"><span className="country-code">{d.key}</span>{d.name}</span><span>{number(d.payments)}</span><span className="rank-rate"><span className="micro-track"><i style={{width:`${d.success_rate??0}%`}}/></span><strong>{percent(d.success_rate)}</strong><ArrowUpRight size={14}/></span></button>)}</div>:<EmptyState/>}
export function RetryFlow({data}:{data:Retry[]}){return data.length?<div className="retry-flow">{data.map((d,i)=><article className="retry-step" key={d.attempt_number}><div className="retry-heading"><span className={i?'step-num lime':'step-num'}>0{d.attempt_number}</span><h3>{i===0?'First attempt':`Retry ${d.attempt_number-1}`}</h3></div><strong>{i===0?percent(d.success_rate):money(d.recovered_value)}</strong><p>{i===0?'approved on first attempt':'recovered payment value'}</p><div className="retry-bottom">{number(d.successes)} of {number(d.attempts)} successful <span>{percent(d.success_rate)}</span></div></article>)}</div>:<EmptyState/>}
export function VolumeBars({data}:{data:Breakdown[]}){const max=Math.max(...data.map(d=>Number(d.processed_volume)),1);return data.length?<div className="volume-bars">{[...data].sort((a,b)=>b.processed_volume-a.processed_volume).map(d=><article key={d.key}><div><h3>{d.name}</h3><strong>{money(d.processed_volume)}</strong></div><div className="bar-track"><span className="accent" style={{width:`${d.processed_volume/max*100}%`}}/></div><p>{number(d.payments)} payments <span>{percent(d.success_rate)} success</span></p></article>)}</div>:<EmptyState/>}
