'use client';
import {ArrowDownLeft,ArrowUpRight,ArrowRight,RotateCcw,SearchX,TriangleAlert} from 'lucide-react';
import type {ReactNode,ButtonHTMLAttributes,SelectHTMLAttributes} from 'react';
import {money,percent,dateLabel,number} from '@/lib/api';
import type {Payment} from '@/lib/types';

export function Button({children,className='',...props}:ButtonHTMLAttributes<HTMLButtonElement>){return <button className={`button ${className}`} {...props}>{children}</button>}
export function Select({label,children,...props}:SelectHTMLAttributes<HTMLSelectElement>&{label:string}){return <label className="select"><span className="sr-only">{label}</span><select {...props}>{children}</select></label>}
export function DatePicker({label,value,onChange}:{label:string;value:string;onChange:(v:string)=>void}){return <label className="date-control"><span>{label}</span><input type="date" value={value} onChange={e=>onChange(e.target.value)} aria-label={label}/></label>}
export function Tooltip({text,children}:{text:string;children:ReactNode}){return <span className="tooltip" tabIndex={0}>{children}<span role="tooltip">{text}</span></span>}
export function Badge({status}:{status:string}){return <span className={`badge ${status}`}><span aria-hidden="true">{status==='recovered'?'↗':status==='failed'?'×':status==='pending'?'◷':'✓'}</span>{status}</span>}
export function Metric({label,value,change,unit='%',inverse=false,note}:{label:string;value:string;change:number|null;unit?:string;inverse?:boolean;note:string}){const good=change!==null&&(inverse?change<=0:change>=0);return <article className="metric"><div className="metric-label">{label}<Tooltip text={note}><span className="info">i</span></Tooltip></div><strong>{value}</strong><div className="metric-foot">{change!==null?<span className={`change ${good?'positive':''}`}>{change>=0?<ArrowUpRight size={14}/>:<ArrowDownLeft size={14}/>} {Math.abs(change).toFixed(1)}{unit}</span>:<span className="no-comparison">—</span>}<span>vs. previous period</span></div></article>}
export function ChartContainer({title,eyebrow,action,children,className=''}:{title:string;eyebrow?:string;action?:ReactNode;children:ReactNode;className?:string}){return <section className={`panel ${className}`}><div className="panel-heading"><div>{eyebrow&&<div className="eyebrow">{eyebrow}</div>}<h2>{title}</h2></div>{action}</div>{children}</section>}
export function EmptyState({text='No payments match this selection.'}:{text?:string}){return <div className="empty" role="status"><SearchX size={28}/><h3>Nothing here yet</h3><p>{text}</p></div>}
export function ErrorState({error,retry}:{error:string;retry:()=>void}){return <div className="error-state" role="alert"><TriangleAlert size={25}/><h2>We couldn’t load your data</h2><p>{error}</p><Button onClick={retry}><RotateCcw size={15}/> Try again</Button></div>}
export function LoadingState(){return <div className="skeletons" role="status" aria-label="Loading payment data"><div className="skeleton wide"/><div className="skeleton-grid">{[0,1,2,3].map(i=><div key={i} className="skeleton"/>)}</div><div className="skeleton chart"/><span className="sr-only">Loading payment data</span></div>}
export function DataTable({rows,onSelect}:{rows:Payment[];onSelect:(id:string)=>void}){return rows.length?<div className="table-scroll"><table><thead><tr><th>Payment / Customer</th><th>Country</th><th>Amount</th><th>Method</th><th>Status</th><th>Attempts</th><th>Date</th><th><span className="sr-only">Details</span></th></tr></thead><tbody>{rows.map(p=><tr key={p.payment_id}><td><button className="text-button payment-id" onClick={()=>onSelect(p.payment_id)}>{p.payment_id}</button><small>{p.customer_name}</small></td><td><span className="country-code">{p.country_code}</span></td><td className="numeric">{money(p.amount_eur,false)}{p.is_outlier&&<small>Flagged for review</small>}</td><td>{p.payment_method}</td><td><Badge status={p.status}/></td><td>{p.attempt_count}</td><td className="nowrap">{dateLabel(p.payment_date)}</td><td><button className="icon-button" aria-label={`Open ${p.payment_id}`} onClick={()=>onSelect(p.payment_id)}><ArrowUpRight size={17}/></button></td></tr>)}</tbody></table></div>:<EmptyState/>}
export function Insight({title,body,tag,onClick,index}:{title:string;body:string;tag:string;onClick:()=>void;index:number}){return <button className="insight" onClick={onClick}><span className="insight-kicker"><span>0{index+1} / {tag}</span><ArrowUpRight size={18}/></span><strong>{title}</strong><p>{body}</p></button>}
export function TextLink({children,onClick}:{children:ReactNode;onClick:()=>void}){return <button className="text-button" onClick={onClick}>{children}<ArrowRight size={15}/></button>}
